/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_myapplication_CserviceInterface */

#ifndef _Included_com_example_myapplication_CserviceInterface
#define _Included_com_example_myapplication_CserviceInterface
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     com_example_myapplication_CserviceInterface
	* Method:    cservice
	* Signature: ()V
	*/
	JNIEXPORT void JNICALL Java_com_example_myapplication_CserviceInterface_cservice
	(JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif